Repository python-chile/pydaydotcl, pull requests merged in 2025-06, with the labels that each got.

#17 Change 10 agenda sedes
  public/images/speakers/Alexis_Alva_Nunez.webp
  public/images/speakers/Alison_Orellana_Rios.webp
  public/images/speakers/Alonso_Astroza.webp
  public/images/speakers/Ariane_Carvajal.webp
  public/images/speakers/Daniel_Hernandez.webp
  public/images/speakers/David_Cortes.webp
  public/images/speakers/Dylan_Oteiza.webp
  public/images/speakers/Flavio_Fabian_Espeche_Nieva.webp
  public/images/speakers/Francisca_Beatriz_Medina_Concha.webp
  public/images/speakers/Francisco_Alfaro.webp
  public/images/speakers/Francisco_Ponce.webp
  public/images/speakers/Francisco_Vergara_Vallejos.webp
  public/images/speakers/Gabriel_Grobier_Romo.webp
  public/images/speakers/Ingrid_Solis_Gonzalez.webp
  public/images/speakers/Jesus_Henriquez.webp
  public/images/speakers/Lia_Da_Silva.webp
  public/images/speakers/Marcelo_Cavieres.webp
  public/images/speakers/Pablo_Jimenez.webp
  public/images/speakers/Pia_Aedo.webp
  public/images/speakers/Sebastian_flores.webp
  public/images/speakers/Valeska_Canales.webp
  public/images/speakers/ana-gonzalez.webp
  public/images/speakers/carla-herrera.webp
  public/images/speakers/carlos-rojas.webp
  public/images/speakers/daniel-castro.webp
  public/images/speakers/felipe-rojas.webp
  public/images/speakers/jorge-mendez.webp
  public/images/speakers/laura-perez.webp
  public/images/speakers/patricia-morales.webp
  public/images/speakers/roberto-gutierrez.webp
  src/app/[city]/page.js
  src/app/page.js
  src/app/talks/page.js
  src/components/FeatureManagement/FeatureGuard.js
  src/components/RegistrationState.js
  src/components/TalkCard.js
  src/data/cities.js
  src/data/talks.js
Labels: enhancement

#20 Fix select color style
  package.json
  src/app/globals.css
Labels: bug

#24 Charla valpo reemplazo
  src/data/sponsors.js
  src/data/talks.js
Labels: enhancement, Urgent
